version: "3.8"
services:
    mongodb:
        image: mongo:4
        container_name: mongodb
        ports: 
            - 27017:27017
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
